[tool.poetry]
name = "habittracker"
version = "0.1.0"
description = ""
authors = ["Tkachenko Vsevolod <sevaatmail@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.2"
djangorestframework = "^3.16.1"
django-cors-headers = "^4.9.0"
python-dotenv = "^1.2.2"
psycopg2-binary = "^2.9.11"
djangorestframework-simplejwt = "^5.5.1"
drf-yasg = "^1.21.15"
celery = "^5.6.2"
redis = "^7.2.1"
requests = "^2.32.5"
python-telegram-bot = "^22.6"
pytest = "^9.0.2"
pytest-django = "^4.12.0"
pytest-cov = "^7.0.0"
factory-boy = "^3.3.3"
pytest-asyncio = "^1.3.0"
asgiref = "^3.11.1"

[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
mypy = "^1.19.1"
black = "^26.1.0"
isort = "^8.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
exclude = 'venv'

[tool.black]
# Максимальная длина строки
line-length = 119
# Файлы, которые не нужно форматировать
exclude = '''
(
  /(
      \.eggs         # Исключить несколько общих каталогов
    | \.git          # в корне проекта
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | dist
  )/
  | foo.py           # Также отдельно исключить файл с именем foo.py
                     # в корне проекта
)
'''

[tool.isort]
# максимальная длина строки
line_length = 119

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = [
    "--nomigrations",
    "--reuse-db",
    "--strict-markers",
]
markers = [
    "django_db: mark test as requiring database",
    "asyncio: mark test as asyncio",
]
asyncio_mode = "auto"
